name: Release

on:
  push:
    paths:
      - 'package.json'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Verify commit message format
      run: |
        if [[ $(git log -1 --pretty=%B) =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Commit message format is correct."
        else
          echo "Error: Commit message format is incorrect. Please use the format 'vX.Y.Z'."
          exit 1
        fi

    - name: Get version from commit
      id: get_version
      run: echo "::set-output name=version::$(git describe --tags --abbrev=0)"

    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
